### ISSUE TITLE
Conflicts with chassis/chassis_openssl

### ISSUE THREAD

**Issue by svandragt** [Chassis/Chassis_XHGui#32]
When the openssl chassis extension is active and the xhgui chassis extensions is added and the box is provisionsed; or when the box is destroyed and a new box is provisioned, the provisioning process fails with the followin error:
  
```bash
   default: /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3 => /Users/sander/dev/_hm/core-sitemaps/puppet/manifests
==> default: Running provisioner: shell...
    default: Running: /var/folders/jj/tspv8xhj24xd0n92js2nz72r0000gn/T/vagrant-shell20191017-3818-1cq8itd.sh
==> default: Running provisioner: puppet...
==> default: Running Puppet with development.pp...
==> default: Error: Duplicate declaration: File[/etc/nginx/sites-available/sitemaps.local.d] is already declared in file /vagrant/extensions/chassis_xhgui/modules/chassis_xhgui/manifests/init.pp:100; cannot redeclare at /vagrant/extensions/chassis_openssl/modules/chassis_openssl/manifests/init.pp:9 on node sitemaps.local
==> default: Error: Duplicate declaration: File[/etc/nginx/sites-available/sitemaps.local.d] is already declared in file /vagrant/extensions/chassis_xhgui/modules/chassis_xhgui/manifests/init.pp:100; cannot redeclare at /vagrant/extensions/chassis_openssl/modules/chassis_openssl/manifests/init.pp:9 on node sitemaps.local
```

1. What operating system do you use? MacOS Mojave

2. What version of Vagrant are you running? 2.2.5

3. Are you using VirtualBox or VMWare and which version are you using? Virtualbox 6.0.12

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
```
# Install a list of extensions automatically
extensions:
  - chassis/chassis_openssl
  - chassis/chassis_xhgui
  - chassis/composer
  - chassis/memcache
  - chassis/nodejs
  - chassis/sequelpro
  - chassis/xdebug

disabled_extensions:
  - chassis/tester
```

5. Do you have any Chassis other extensions installed? If so, what are they?
See above

**Comment by BronsonQuick** [comment]
Thanks so much for reporting this issue. I hadn't tested those two extensions today. To fix this I believe we'll need to wrap that declaration in a `if ! defined`. There's an example of the format here: https://github.com/Chassis/v8js/blob/master/modules/v8js/manifests/extension.pp#L49

Unfortunately I won't have my laptop around for a couple more weeks to do a PR and some testing.

**Comment by svandragt** [comment]
I’ll see what I can do.

**Comment by BronsonQuick** [comment]
Thanks so much!

**Comment by BronsonQuick** [comment]
I couldn't replicate this. Here's what I did to try to replicate it:
1. Ran `vagrant up` with the following config:
```
hosts:
  - sitemaps.local
extensions:
  - chassis/chassis_openssl
  - chassis/composer
  - chassis/memcache
  - chassis/nodejs
  - chassis/sequelpro
  - chassis/xdebug
```
2. Run `vagrant provision` with the following config:
```
hosts:
  - sitemaps.local
extensions:
  - chassis/chassis_openssl
  - chassis/composer
  - chassis/memcache
  - chassis/nodejs
  - chassis/sequelpro
  - chassis/xdebug
  - chassis/chassis_xhgui
```
There might have been some extension updates since this issue was opened so I'm going to close it for now but if you are still having this issue @svandragt then please reopen it with more information for me and I'll try to replicate it again. Thanks!
