### ISSUE TITLE
Not possible to install globally

### ISSUE THREAD

**Issue by svandragt** [Chassis/Chassis_XHGui#39]
I like this extension, so I tried to install this extension globally:

```
cd ~/.chassis/extensions
git clone --recursive git@github.com:Chassis/chassis_xhgui.git
cd $PROJECT; vagrant provision
```
No dependencies like xhprof and mongodb are installed. When adding the extension to the content/config.yaml file everything is installed.

**Comment by BronsonQuick** [comment]
Thanks for the bug report @svandragt! I wasn't aware of this issue. I'd say this affects any global extensions that have dependencies so I've opened this issue upstream: https://github.com/Chassis/Chassis/issues/823 I'll close this out for now and hopefully find some time over the weekend to dig into that for you.
